### ISSUE TITLE
Update CivicTech Toolkit with Released Content

### ISSUE THREAD

**Issue by dougakers** [CivicTechWR/OrgOrg#4]
The civic technology toolkit is no longer in beta. Update/refresh our shared drive with the released content.

**Comment by KristinaTaylor** [comment]
It's probably ideal if we branch/create copies of the stuff we want to use. If we don't, I worry we'll end up accidentally editing the master template. :)

**Comment by dougakers** [comment]
This could be good practice for me on git. Next time we are chatting walk me through how this would be done if you don't mind.

**Comment by tonge** [comment]
It would be great to do a 5-10 minute presentation on GitHub. Everyone knows it, but not everyone knows how to use it well or its benefits. Many people are afraid to ask, so I think that would be a great topic for us to cover.

________________________________

**Comment by KristinaTaylor** [comment]
Looks like the toolkit is now back online in a published state: https://medium.com/code-for-canada/lessons-from-building-code-for-canadas-civic-tech-toolkit-74625e740515

**Comment by dougakers** [comment]
Added to OrgOrg repository... and maybe somewhere else by accident though I can't find it on the site even though that's my default location and the first time I didn't specify OrgOrg
