### ISSUE TITLE
Create a meetup group

### ISSUE THREAD

**Issue by KristinaTaylor** [CivicTechWR/OrgOrg#7]
Since new meetup groups can trigger geographic based alerts, wait to create the group until after #6 is done and we have an agenda for the first event.

When group is created, make sure to update the website and the  [Account Info](https://github.com/CivicTechWR/OrgOrg/wiki/Organizational-Account-Info) page with the owner of the keys

**Comment by KristinaTaylor** [comment]
Created the group... still need to upload logos, create first event, etc.

http://meetu.ps/c/3vTmC/lTxgH/a

**Comment by tonge** [comment]
Logos if you need them

________________________________
